### PR TITLE
fix the edge case of double leading slash when rebuilding request

### LINKED ISSUE #166: ChainRouter does not handle URLs starting with two slashes properly
This issue follows rejected pull requests: https://github.com/symfony-cmf/Routing/pull/147 and https://github.com/symfony-cmf/Routing/pull/152
and is still not fixed even after merging: https://github.com/symfony-cmf/Routing/pull/163 (sorry for not commenting earlier).

If you pass `//test` as an `$url` parameter into `ChainRouter::match()` method and you have `RequestMatcherInterface` in the chain, it tries to match it as pathinfo `/` with host `test` instead of matching as pathinfo `//test`.

See this failing test: https://github.com/symfony-cmf/Routing/compare/master...sustmi:test-for-matching-double-slash?expand=1

### PR DESCRIPTION
**Pull request by dbu**
fix #166

@sustmi you are right. as it turns out, even specifying the host explicitly, `Request::create('//test')` considers the path as a domain. i now rebuild the full URL, i do hope this now works.

note that you will need to do setContext with the RequestContext for this to work. if there is no request context, we don't do anything more than before the fix.

### CODE REVIEW

File: ChainRouter.php [hunk 1]
```diff
@@ -291,8 +291,19 @@ private function rebuildRequest($uri)
                 $server['HTTP_HOST'] .= ':'.$this->context->getHttpPort();
             }
         }
+        // use the array field to have both domain and port.
+        if (isset($server['HTTP_HOST'])) {
+            $pathinfo = $server['HTTP_HOST'].$pathinfo;
+        } else {
+            $pathinfo = 'localhost'.$pathinfo;
```
Comment (dbu) [inline ChainRouter.php]: do we want to do this? and if we do, should we do the same for the case without RequestContext being set at all?

**Comment by sustmi** [comment]
Hi @dbu . I tried the fix and it works for me.

File: ChainRouter.php (hunk 1 above)
Comment (sustmi) [inline ChainRouter.php]: I hope the question is not on me. I cannot comment on the code because I do not understand it.
I try to keep away from anything that comes into contact with `preparePathInfo()` and `prepareBaseUrl()` methods of `Request`, because it's a black magic.

Comment (dbu) [inline ChainRouter.php]: this is more a question to @lsmith77

Comment (lsmith77) [inline ChainRouter.php]: I am not deep enough into this PR to really tell either .. @tobion might know best in general as he knows the entire routing topic really well ..

File: ChainRouter.php [hunk 2]
```diff
@@ -255,26 +255,26 @@ public function generate($name, $parameters = array(), $absolute = UrlGeneratorI
...
         }
 
         $server = array();
-        if ($this->context->getHost()) {
-            $server['SERVER_NAME'] = $this->context->getHost();
-            $server['HTTP_HOST'] = $this->context->getHost();
-        }
         if ($this->context->getBaseUrl()) {
-            $uri = $this->context->getBaseUrl().$uri;
+            $pathinfo = $this->context->getBaseUrl().$pathinfo;
```
Comment (Tobion) [inline ChainRouter.php]: pathinfo is the path without the base url according to CGI spec. so the variable naming reuse is confusing.

File: ChainRouter.php [hunk 3]
```diff
@@ -291,8 +291,19 @@ private function rebuildRequest($uri)
...
             }
         }
+        // use the array field to have both domain and port.
+        if (isset($server['HTTP_HOST'])) {
+            $pathinfo = $server['HTTP_HOST'].$pathinfo;
+        } else {
+            $pathinfo = 'localhost'.$pathinfo;
+        }
+        if ('https' === $this->context->getScheme()) {
+            $pathinfo = 'https://'.$pathinfo;
```
Comment (Tobion) [inline ChainRouter.php]: same, clearly not the $pathinfo

File: ChainRouter.php [hunk 4]
```diff
@@ -255,26 +255,26 @@ public function generate($name, $parameters = array(), $absolute = UrlGeneratorI
...
-        }
         if ($this->context->getBaseUrl()) {
-            $uri = $this->context->getBaseUrl().$uri;
+            $pathinfo = $this->context->getBaseUrl().$pathinfo;
             $server['SCRIPT_FILENAME'] = $this->context->getBaseUrl();
             $server['PHP_SELF'] = $this->context->getBaseUrl();
         }
+        if ($this->context->getHost()) {
+            $server['SERVER_NAME'] = $this->context->getHost();
+            $server['HTTP_HOST'] = $this->context->getHost();
```
Comment (Tobion) [inline ChainRouter.php]: IMO it's easier and cleaner to really build a full URI and then pass this to Request::create. Then you do not need to deal with the server variables at all. The request method is doing that itself: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L330

File: ChainRouter.php [hunk 5]
```diff
@@ -255,26 +255,26 @@ public function generate($name, $parameters = array(), $absolute = UrlGeneratorI
...
         $server = array();
-        if ($this->context->getHost()) {
-            $server['SERVER_NAME'] = $this->context->getHost();
-            $server['HTTP_HOST'] = $this->context->getHost();
-        }
         if ($this->context->getBaseUrl()) {
-            $uri = $this->context->getBaseUrl().$uri;
+            $pathinfo = $this->context->getBaseUrl().$pathinfo;
             $server['SCRIPT_FILENAME'] = $this->context->getBaseUrl();
             $server['PHP_SELF'] = $this->context->getBaseUrl();
```
Comment (Tobion) [inline ChainRouter.php]: the base url server variables are probably the only ones that you need to deal with as done here because that cannot be deducated from the URI alone.

**Comment by Tobion** [comment]
The query string handling seems to be missing (which is not that important because it's not used by the routing itself AFAIK, but for consistency).

**Comment by dbu** [comment]
thanks a lot for the feedback. indeed i do not need all that header
stuff. i just pushed an updated version.

> The query string handling seems to be missing

i don't understand what you mean here. we just pass around the pathinfo
that was given to us to match. is that without query parameters? or are
the query parameters only handled after the route has been matched?
should i simply append context->getQueryString() to the uri?

**Comment by Tobion** [comment]
Yes, the pathinfo does not contain the query string. Just add the query string at the end. See https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1067

**Comment by Tobion** [comment]
Otherwise looks good now :+1:

**Comment by dbu** [comment]
i think contrary to other parts, the query parameters are actually used in the `create` method. but i added them to the url nontheless for completeness. will merge when its green.

as we discussed yesterday, it would be really nice to have a stand alone Request class cleanly separated from HTTP header and other black magic, with a separate RequestBuilder to build request instances from HTTP. i hope for symfony 4 :-)

File: ChainRouter.php [hunk 6]
```diff
@@ -255,42 +255,32 @@ public function generate($name, $parameters = array(), $absolute = UrlGeneratorI
...
-                $server['HTTP_HOST'] .= ':'.$this->context->getHttpPort();
-            }
+        $host = $this->context->getHost() ?: 'localhost';
+        if ('https' === $this->context->getScheme() && 443 !== $this->context->getHttpsPort()) {
+            $host .= ':'.$this->context->getHttpsPort();
+        }
+        if ('http' === $this->context->getScheme() && 80 !== $this->context->getHttpPort()) {
+            $host .= ':'.$this->context->getHttpPort();
         }
+        $uri = $this->context->getScheme().'://'.$host.$uri.$this->context->getQueryString();
```
Comment (Tobion) [inline ChainRouter.php]: this does not work. it's missing the `?` before the query string. this is why i linked the exmaple implementation https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1067

Comment (dbu) [inline ChainRouter.php]: argh. thanks for spotting. i fixed it in the master branch as i already
merged this.
